//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ejemploSOAP.webservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:createSale", ConfigurationName="webservice.createSalePortType")]
    public interface createSalePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:createSale#createSale", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ejemploSOAP.webservice.ResultData createSale(string strUser, string strPassword, string strXML, string strEnvironment, string strInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:createSale#createSale", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ejemploSOAP.webservice.ResultData> createSaleAsync(string strUser, string strPassword, string strXML, string strEnvironment, string strInstance);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:createSale")]
    public partial class ResultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strStatusField;
        
        private string strCodeField;
        
        private string strResultField;
        
        /// <remarks/>
        public string strStatus {
            get {
                return this.strStatusField;
            }
            set {
                this.strStatusField = value;
                this.RaisePropertyChanged("strStatus");
            }
        }
        
        /// <remarks/>
        public string strCode {
            get {
                return this.strCodeField;
            }
            set {
                this.strCodeField = value;
                this.RaisePropertyChanged("strCode");
            }
        }
        
        /// <remarks/>
        public string strResult {
            get {
                return this.strResultField;
            }
            set {
                this.strResultField = value;
                this.RaisePropertyChanged("strResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface createSalePortTypeChannel : ejemploSOAP.webservice.createSalePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class createSalePortTypeClient : System.ServiceModel.ClientBase<ejemploSOAP.webservice.createSalePortType>, ejemploSOAP.webservice.createSalePortType {
        
        public createSalePortTypeClient() {
        }
        
        public createSalePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public createSalePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public createSalePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public createSalePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ejemploSOAP.webservice.ResultData createSale(string strUser, string strPassword, string strXML, string strEnvironment, string strInstance) {
            return base.Channel.createSale(strUser, strPassword, strXML, strEnvironment, strInstance);
        }
        
        public System.Threading.Tasks.Task<ejemploSOAP.webservice.ResultData> createSaleAsync(string strUser, string strPassword, string strXML, string strEnvironment, string strInstance) {
            return base.Channel.createSaleAsync(strUser, strPassword, strXML, strEnvironment, strInstance);
        }
    }
}
