using ejemploSOAP.webservice;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ejemploSOAP
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            webservice.createSalePortTypeClient ws = new createSalePortTypeClient();
            string strXML = "eyJPYnNlcnZhY2lvbiI6eyJPYnNlcnZhY2lvbiI6ImZhbHNlIn0sIm5uIjp7Im5uIjp7IklWQSI6eyIxNiI6IjAuMzIifX19LCJubmYiOnsibm5mIjp7IklWQSI6eyIxNiI6eyJWYWxvciI6IjAuMzIifX19fSwib3JnIjp7ImxvZ28iOiJBcHBtaW5pc3RyYS5wbmcifSwiQ29ycmVvIjp7IkNvcnJlbyI6IiJ9LCJCYXNpY29zIjp7Ik1vbmVkYSI6Ik1YTiIsIk1ldG9kb1BhZ28iOiJQVUUiLCJOdW1DdGFQYWdvIjoiOCIsIkx1Z2FyRXhwZWRpY2lvbiI6IjIyMDE0IiwiVmVyc2lvbiI6IjMuMyIsIlNlcmllIjoiQSIsIkZvbGlvIjoiMyIsIkZlY2hhIjoiMjAxOS0wNS0wOFQyMzo1OTo1NyIsIlNlbGxvIjoiIiwiRm9ybWFQYWdvIjoiMDQiLCJUaXBvRGVDb21wcm9iYW50ZSI6IkkiLCJOb0NlcnRpZmljYWRvIjoiIiwiQ2VydGlmaWNhZG8iOiIiLCJTdWJUb3RhbCI6IjIuMDAiLCJUb3RhbCI6IjIuMzIifSwidGlwb0ZhY3R1cmEiOiJmYWN0dXJhIiwiUmVhbGFjaW9uYWRvcyI6eyJ4bWwiOiIiLCJjYWRlbmEiOiIifSwiRW1pc29yIjp7IlJlZ2ltZW5GaXNjYWwiOiIiLCJSZmMiOiIiLCJOb21icmUiOiIifSwiUmVjZXB0b3IiOnsiUmZjIjoiWEFYWDAxMDEwMTAwMCIsIk5vbWJyZSI6IkZBQ1RVUkEgR0VORVJJQ0EiLCJVc29DRkRJIjoiRzAxIn0sIkNvbmNlcHRvcyI6eyJjb25jZXB0b3MiOiI8Y2ZkaTpDb25jZXB0byBDbGF2ZVByb2RTZXJ2PSc3MDEwMTUwMScgTm9JZGVudGlmaWNhY2lvbj0nU0NJMTUwYScgQ2FudGlkYWQ9JzEnIENsYXZlVW5pZGFkPSdIODcnIFVuaWRhZD0nUGllemEnIERlc2NyaXBjaW9uPSdBR1VBIFBVUklGSUNBREEgQ0lFTCAxIExJVFJPJyBWYWxvclVuaXRhcmlvPScxLjAwMDAwMCcgSW1wb3J0ZT0nMS4wMDAwMDAnPjxjZmRpOkltcHVlc3Rvcz48Y2ZkaTpUcmFzbGFkb3M+PGNmZGk6VHJhc2xhZG8gQmFzZT0nMS4wMDAwMDAnIEltcHVlc3RvPScwMDInIFRpcG9GYWN0b3I9J1Rhc2EnIFRhc2FPQ3VvdGE9JzAuMTYwMDAwJyBJbXBvcnRlPScwLjE2MDAwMCcgXC8+PFwvY2ZkaTpUcmFzbGFkb3M+PFwvY2ZkaTpJbXB1ZXN0b3M+PFwvY2ZkaTpDb25jZXB0bz48Y2ZkaTpDb25jZXB0byBDbGF2ZVByb2RTZXJ2PScwMTAxMDEwMScgTm9JZGVudGlmaWNhY2lvbj0nNzUwNDU2MjMnIENhbnRpZGFkPScxJyBDbGF2ZVVuaWRhZD0nSDg3JyBVbmlkYWQ9J1BpZXphJyBEZXNjcmlwY2lvbj0nVHJpZGVudCAgTWVudGEgNCBwYXN0aWxsYXMnIFZhbG9yVW5pdGFyaW89JzEuMDAwMDAwJyBJbXBvcnRlPScxLjAwMDAwMCc+PGNmZGk6SW1wdWVzdG9zPjxjZmRpOlRyYXNsYWRvcz48Y2ZkaTpUcmFzbGFkbyBCYXNlPScxLjAwMDAwMCcgSW1wdWVzdG89JzAwMicgVGlwb0ZhY3Rvcj0nVGFzYScgVGFzYU9DdW90YT0nMC4xNjAwMDAnIEltcG9ydGU9JzAuMTYwMDAwJyBcLz48XC9jZmRpOlRyYXNsYWRvcz48XC9jZmRpOkltcHVlc3Rvcz48XC9jZmRpOkNvbmNlcHRvPiIsImNvbmNlcHRvc09yaSI6Inw3MDEwMTUwMXxTQ0kxNTBhfDF8SDg3fFBpZXphfEFHVUEgUFVSSUZJQ0FEQSBDSUVMIDEgTElUUk98MS4wMDAwMDB8MS4wMDAwMDB8MS4wMDAwMDB8MDAyfFRhc2F8MC4xNjAwMDB8MC4xNjAwMDB8fDAxMDEwMTAxfDc1MDQ1NjIzfDF8SDg3fFBpZXphfFRyaWRlbnQgIE1lbnRhIDQgcGFzdGlsbGFzfDEuMDAwMDAwfDEuMDAwMDAwfDEuMDAwMDAwfDAwMnxUYXNhfDAuMTYwMDAwfDAuMTYwMDAwfCJ9LCJJbXB1ZXN0b3MiOnsidG90YWxJbXB1ZXN0b3NJZXBzIjoiMCIsImlzciI6IiIsIml2YSI6InwwMDJ8VGFzYXwwLjE2MDAwMHwwLjMyfDAuMzIiLCJ0b3RhbEltcHVlc3Rvc1JldGVuaWRvcyI6IjAuMDAiLCJ0b3RhbEltcHVlc3Rvc1RyYXNsYWRhZG9zIjoiMC4zMiIsIml2YXMiOiI8Y2ZkaTpUcmFzbGFkb3M+PGNmZGk6VHJhc2xhZG8gSW1wdWVzdG89JzAwMicgVGlwb0ZhY3Rvcj0nVGFzYScgVGFzYU9DdW90YT0nMC4xNjAwMDAnIEltcG9ydGU9JzAuMzInIFwvPjxcL2NmZGk6VHJhc2xhZG9zPiJ9LCJDb21wbGVJbXB1ZXMiOnsieG1sQ29tcGxlIjoiIiwiY2FkZW5hQ29tcGxlIjoiIn19";
            ResultData result = ws.createSale("Analista", "Analista1", strXML, "DEV_33", "laespecial");
            string data = result.strResult;
            int i = 0;
        }
    }
}
